version: '3.8'

services:
  socket-server:
    image: prayag78/codesync-socket-server:latest
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: prayag78/codesync-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SOCKET_URL=http://socket-server:8000
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    depends_on:
      - socket-server
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
